# Generated by Django 4.1 on 2022-11-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200, unique=True, verbose_name='Reference name')),
                ('object_3d', models.FileField(blank=True, null=True, upload_to='flowers_obj', verbose_name='3D Image')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200, unique=True, verbose_name='reference')),
                ('object_3d', models.FileField(blank=True, null=True, upload_to='topics_obj', verbose_name='3D Image')),
            ],
        ),
        migrations.CreateModel(
            name='Vase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200, unique=True, verbose_name='reference')),
                ('object_3d', models.FileField(blank=True, null=True, upload_to='vases_obj', verbose_name='3D Image')),
                ('max', models.PositiveIntegerField(default=0, verbose_name='max flowers')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('vase_position', models.JSONField(blank=True, null=True)),
                ('refernce_json_flowers', models.JSONField(blank=True, null=True)),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('position_file', models.JSONField(verbose_name='position_file')),
                ('vase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate.vase')),
            ],
        ),
    ]
