# Generated by Django 4.1 on 2022-09-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='Arabic name')),
                ('image', models.ImageField(upload_to='flowers_images', verbose_name='Image')),
                ('object_3d', models.FileField(upload_to='flowers_obj', verbose_name='3D Image')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('special_price', models.FloatField(default=0.0, verbose_name='Promo Price')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='Arabic name')),
                ('image', models.ImageField(upload_to='topics_images', verbose_name='Image')),
                ('object_3d', models.FileField(upload_to='topics_obj', verbose_name='3D Image')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='Arabic name')),
                ('image', models.ImageField(upload_to='vases_images', verbose_name='Image')),
                ('object_3d', models.FileField(upload_to='vases_obj', verbose_name='3D Image')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('special_price', models.FloatField(default=0.0, verbose_name='Promo Price')),
                ('max', models.PositiveIntegerField(default=0, verbose_name='max flowers')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
