# Generated by Django 4.1 on 2022-11-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='flower',
            name='object_3d',
            field=models.FileField(blank=True, null=True, upload_to='flowers_obj', verbose_name='3D Image'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='object_3d',
            field=models.FileField(blank=True, null=True, upload_to='topics_obj', verbose_name='3D Image'),
        ),
        migrations.AlterField(
            model_name='vase',
            name='object_3d',
            field=models.FileField(blank=True, null=True, upload_to='vases_obj', verbose_name='3D Image'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('position_file', models.JSONField(verbose_name='position_file')),
                ('vase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate.vase')),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generate.categoryflower'),
        ),
    ]
