# Generated by Django 4.1 on 2022-11-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0003_flower_id_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='id_reference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
