# Generated by Django 4.1 on 2022-11-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0004_alter_flower_id_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='vase',
            name='id_reference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
