# Generated by Django 4.1 on 2022-12-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0005_vase_id_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='id_reference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
