# Generated by Django 4.1 on 2022-12-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0007_position_quantity_1_position_quantity_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='quantity_4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='rose_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
